n = int(input('Quantos termos você deseja ver?  '))
cont = 3
n1 = 0
n2 = 1
print(' {}  {} '.format(n1,n2), end=' ')
while cont <= n:
    n3 = n1 + n2
    print(' {} '.format(n3), end=' ')
    n1 = n2
    n2 = n3
    cont = cont + 1
